name: CI/CD for Express.js app (Node.js)

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-tests:
    name: Test Express.js REST-API
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    strategy:
      matrix:
        node-version: [12.x] # [12.x, 13.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest] # [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Print a greeting
      run: echo Hello everyone! We are executing all tests here!

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npm test

  release-production:
    name: Release Production Build
    needs: run-tests
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [12.x] # [12.x, 13.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Debug Output
      run: |
        echo npm is now installing ..
    - run: npm install
    - name: Debug Output
      run: |
        echo npm is invoking target 'release'
    - run: npm run release

  # TODO upload JS build artefact here!

  upload-production-release:
    name: Upload production build to artifact
    needs: release-production
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p public
      - shell: bash
        run: |
          echo Test Text! > public/public.txt
      - name: Upload hello world file
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/public.txt

  upload-data-job:
    name: Upload data to artifact
    needs: release-production
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p hello-world
      - shell: bash
        run: |
          echo Hello World! > hello-world/hello-world.txt
      - name: Upload hello world file
        uses: actions/upload-artifact@v1
        with:
          name: hello-world
          path: hello-world/hello-world.txt

  download-data-job:
    name: Download data from artifact
    needs: upload-data-job
    runs-on: windows-latest
    steps:
      - name: Download hello world file
        uses: actions/download-artifact@v1
        with:
          name: hello-world
          path: hello-world/hello-world.txt

  conditional-job:
    name: Only executed if upload job succeeded
    needs: download-data-job
    runs-on: windows-latest
    steps:
    - name: Print a message
      run: echo The releae pipeline has been completed!
