name: CI/CD for Express.js app (Node.js)

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  release-version: "1.0.0"

jobs:

  run-jest-tests:
    name: Test Jest Express.js REST-API
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.18] # [12.x, 13.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest] # [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Print a greeting
      run: echo Hello everyone! We are executing all JEST tests here!

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npm run jest

    - name: Upload Test Coverage Report Artefact
      uses: actions/upload-artifact@v1
      with:
        name: testCoverage-v${{ env.release-version }}
        path: public/coverage

  run-linter:
    name: ESLint on app sourcecode
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.18] # [12.x, 13.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest] # [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Print a greeting
      run: echo Hello everyone! We are now linting the code ..

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: npm run eslint

    - run: mkdir -p public
    - run: npm run eslintReport
    - name: Upload Linter Report Artefact
      uses: actions/upload-artifact@v1
      with:
        name: linterReport-v${{ env.release-version }}
        path: public/linter-report.xml

  generate-jsdoc:
    name: JSDoc generation on app sourcecode
    needs: [run-jest-tests, run-linter]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.18] # [12.x, 13.x, 14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        os: [ubuntu-latest] # [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Print a greeting
      run: echo Hello everyone! We are now generating JSDoc documentation for all JavaScript source codes ..

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
    - run: mkdir -p public
    - run: npm run jsdoc

    - name: Upload JSDoc documentation
      uses: actions/upload-artifact@v1
      with:
        name: jsdoc-v${{ env.release-version }}
        path: public/jsdoc

  build-and-release-production:
    name: Create and Release Production Build
    needs: generate-jsdoc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - name: Debug Output
      run: |
        echo npm is now installing ..
    - name: Install npm packages
      run: npm install

    - name: Debug Output
      run: |
        echo npm is invoking target 'release'

    - name: Build Production Release
      run: npm run release

    - name: Upload Release Artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-bundle-v${{ env.release-version }}
        path: public/app-bundle.js

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: Release v${{ env.release-version }}
        tag: ${{ env.release-version }}
        artifacts: "public/app-bundle.js"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        omitBody: true
        removeArtifacts: true
